### ISSUE TITLE
Null pointer exception after training with Files Data Sources

### ISSUE THREAD

**Issue by DanielTakeshi** [BIDData/BIDMach#117] opened 2016-04-29 16:06 UTC
BIDMach: b4b21ec955851375f94d68ef5e33b3ba74bf5059
BIDMat: e69e2abbf8a59d30728a46b2062045c158a3ef2e
OS: Linux

The BIDMach/BIDMat versions are from March 15 but I have observed the same behaviour using the latest version as of today.

When I train using a Files Data Source, at the end of the training, I get a null pointer exception. As shown in the following excerpt, the last pass over the data finishes and the total training time was 263 seconds. Then I prepare the prediction code. But _before_ that happens, there is a null pointer exception and we can't seem to close the file.

This is with Net.scala but I have observed the same thing with RandomForests.scala, and in any case, the issue seems to be in the FileSource.close() method.

It doesn't seem to affect the performance of the predictor, as the model matrices (e.g., weights in a neural network) are stored correctly. It's just an isolated incidence about closing files.

I am using `lookahead=0` for the Files Data Source, and in this particular case there were two files as input, but this always happens with this data source type, even if there is just one file. To reproduce the error, train using Net.scala (on arbitrary data) using a Files Data Source.

```
90.00%, ll=-0.39710, gf=84.784, secs=263.4, GB=10.50, MB/s=39.87, GPUmem=0.965825
93.00%, ll=-0.43401, gf=84.794, secs=263.6, GB=10.51, MB/s=39.87, GPUmem=0.965825
96.00%, ll=-0.40861, gf=84.803, secs=263.7, GB=10.52, MB/s=39.88, GPUmem=0.965825
99.00%, ll=-0.44796, gf=84.813, secs=263.8, GB=10.52, MB/s=39.88, GPUmem=0.965825
100.00%, ll=0.00000, gf=84.814, secs=263.8, GB=10.52, MB/s=39.88, GPUmem=0.965825
Time=263.8380 secs, gflops=84.81
java.lang.NullPointerException
  at BIDMach.datasources.FileSource.close(FileSource.scala:308)
  at BIDMach.Learner.wrapUp(Learner.scala:176)
  at BIDMach.Learner.retrain(Learner.scala:84)
  at BIDMach.Learner.train(Learner.scala:69)
  ... 54 elided
mm0: BIDMach.Learner = Learner(BIDMach.datasources.MatSource@7946c637,BIDMach.networks.Net@157f8315,null,null,BIDMach.datasinks.MatSink@6676e2b9,BIDMach.networks.Net$PredOptions@71f143d)
mopts0: BIDMach.networks.Net.PredOptions = BIDMach.networks.Net$PredOptions@71f143d
mopts0.batchSize: Int = 1000
mopts0.addConstFeat: Boolean = false
Predicting
 1.00%, ll=0.00000, gf=319.823, secs=0.0, GB=0.00, MB/s=385.33, GPUmem=0.97
 2.00%, ll=0.00000, gf=319.823, secs=0.0, GB=0.00, MB/s=385.33, GPUmem=0.97
 3.00%, ll=0.00000, gf=359.801, secs=0.0, GB=0.00, MB/s=433.50, GPUmem=0.97
```

**Comment by jcanny** [comment] 2016-04-30 07:53
Hi Daniel,
I cant reproduce the problem and from the line numbers you must be running an old version of the code. Could you please update to the current version?

**Comment by DanielTakeshi** [comment] 2016-04-30 22:40
I've updated to:

BIDMat f29887318875811381229c939c55007631d1630e (April 28)
BIDMach: 33424d8a604a2ccc48cd8d0bb4801af31b3ab90a (April 28)

Er, I just saw you've added three more updates since then, but FileSource.scala (last updated 13 days ago) and Learner.scala (last updated a month ago) are the same as they are now (April 30).

```
97.00%, ll=-0.51917, gf=145.457, secs=2204.3, GB=91.52, MB/s=41.52, GPUmem=0.965194
98.00%, ll=-0.49098, gf=145.460, secs=2204.7, GB=91.54, MB/s=41.52, GPUmem=0.965194
99.00%, ll=-0.50088, gf=145.462, secs=2205.1, GB=91.56, MB/s=41.52, GPUmem=0.965194
100.00%, ll=-0.38274, gf=145.464, secs=2205.5, GB=91.58, MB/s=41.52, GPUmem=0.965194
Time=2205.5281 secs, gflops=145.46
java.lang.NullPointerException
  at BIDMach.datasources.FileSource.close(FileSource.scala:328)
  at BIDMach.Learner.wrapUp(Learner.scala:178)
  at BIDMach.Learner.retrain(Learner.scala:85)
  at BIDMach.Learner.train(Learner.scala:70)
  ... 54 elided
mm: BIDMach.Learner = Learner(BIDMach.datasources.MatSource@211da3a4,BIDMach.networks.Net@20e274f8,null,null,BIDMach.datasinks.MatSink@736d56a5,BIDMach.networks.Net$PredOptions@f53a5d7)
mopts: BIDMach.networks.Net.PredOptions = BIDMach.networks.Net$PredOptions@f53a5d7
mopts.batchSize: Int = 1000 
mopts.addConstFeat: Boolean = false
Predicting
 1.00%, ll=0.00000, gf=385.101, secs=0.0, GB=0.00, MB/s=289.00, GPUmem=0.96
 2.00%, ll=0.00000, gf=440.116, secs=0.0, GB=0.00, MB/s=330.29, GPUmem=0.96
```

**Comment by jcanny** [comment] 2016-05-01 16:59
OK fixed now. It helps to know the line number that threw the exception.

**Closed by jcanny** 2016-05-01 16:59 UTC

**Comment by DanielTakeshi** [comment] 2016-05-02 15:20
Yes, it works now. Thanks.
